### ISSUE TITLE
show warning when blips are dropped

### ISSUE THREAD

**Issue by emirose** [thoughtworks/build-your-own-radar#14]
Hi,

This radar tool has been really useful, but I found the behavior when there are too many blips for a certain quadrant/ring very confusing. I was surprised to find that not all my blips were showing up and saw that in radar.js blips that are not successfully placed without a collision after 100 attempts are silently dropped. It might be good to give a warning when a blip is dropped or just set an explicit cap on number of blips for each section.

**Comment by rdoh** [comment]
We agree this is a problem. We weren't sure how often the issue would occur, since we didn't know how many blips people would be having.

I think showing a warning is the easiest "fix" right now. We'd gladly merge a pull request for that :)

I prefer that to capping the number of blips since it'd be very difficult to choose a good cap (different people having different screen sizes, etc).

**Comment by emirose** [comment]
Cool, thanks for the reply. I'll work on a PR to add a warning then :-).

Have you looked into any other ways to avoid blip collisions? I was wondering if using d3 force might work.

**Comment by thenano** [comment]
Thanks @emirose! I also agree the silent dropping is not ideal, but I guess people though it was a better solution than the previous one, which was to make the whole rendering non-deterministic - it would try forever to find a spot, and sometimes would never stop.
I for one thought it was artistic, but not sure others would agree :)
Other possibilities I thought about as well: 
- we could actually calculate how many blips would fit in that ring because we know the area of the ring and the area of the blip, so we would only really need to display a warning in that case.
- we could start allowing collisions after a certain number of iterations, by reducing the collision area
- we could actually randomly pull positions off of a position matrix, that way we wouldn't even have to bother with calculating collision as only non-colliding positions would be available.

Out of all of the above, my personal preference is the 3rd, but probably the hardest.

**Comment by filipesabella** [comment]
Oh just caught up with the current issues. I created a PR to try and address this:
https://github.com/thoughtworks/build-your-own-radar/pull/26

**Comment by thenano** [comment]
Thanks!

I'm fine to merge the PR unless someone here has any objections, @rdoh?

**Comment by rdoh** [comment]
Looks great. Thanks Filipe. I see three is commentary ongoing on the PR
itself so will leave it to the team there.
