### ISSUE TITLE
edit the visualization: in first glance, nodes just show some numbers, we need person's name instead

### ISSUE THREAD

**Issue by maryamltu** [thoughtworks/build-your-own-radar#166]
I want to change the view of radar at first glance, I mean, instead of numbers in rings, I want to show for example the name of person how work on this technology. Do u catch? how I can do that? 
Also what is random distribution to put node in visualization? I changed some values in excel sheet, and now all of nodes are centered in one place, just a few are in far place, not like yours in a good distributed place and good look. I don't understand why?

**Comment by marisahoenig** [comment]
Hi @maryamltu. The BYOR is meant to act similarly to the [Thoughtworks Tech Radar](https://www.thoughtworks.com/radar) tool. If you'd like to customize it to use names instead of numbers, you would need to fork the repo and make your own adjustments. Unfortunately, we do not plan to stray away from numbers in the hosted version on radar.thoughtworks.com.

I'm not sure I understand your second question about the nodes all being centered in one place. If this is still an issue, can you clarify? For the time being, I am closing this issue since it is old — however, please reopen if you need further support. Thank you!
