### ISSUE TITLE
Chrome not prompting for Google Sheet authentication, even when pop-ups allowed

### ISSUE THREAD

**Issue by jacobmclocklin** [thoughtworks/build-your-own-radar#314]
Hello -

We use BYOR hosted on radar.thoughtworks.com. We supply a Google Sheet that requires authentication. A while ago (1+ months), all browsers would successfully request authentication from Google for our Sheet, as long as pop-ups were allowed for the current URL. However, now Chrome will not prompt for authentication at all. I have double-checked that pop-ups are allowed. 

Firefox and Safari are prompting for authentication correctly, and the radar renders correctly.

**Comment by marisahoenig** [comment]
Hey @jacobmclocklin! Thanks for bringing this to our attention. In Chrome, when the pop-up doesn't show up, does the page just keep saying it's loading? If not, what's the experience?

**Comment by jacobmclocklin** [comment]
Thank you for the reply! I apologize for not including this detail in my original submission.

The experience in Chrome for me is the loading screen with no indication that authentication has been attempted or failed. The loading spinner on the page keeps spinning (the square shaped one). The message is like “Building your technology radar”.

Chrome version in use: 112

**Comment by marisahoenig** [comment]
@jacobmclocklin Thanks for the info! I'm actually getting similar behavior when I try a private sheet, which used to work for me — and, a public sheet doesn't cause the same issue. I'm bringing this to the rest of the team and we'll see if we can debug. Will keep you updated! Thanks 😊

**Comment by devansh-sharma-tw** [comment]
Hi @jacobmclocklin , we've looked into this behavior with private Google Sheets, and it seems like the issue might be with a recent update made to the 1Password Chrome extension :) The issue is described [here](https://1password.community/discussion/139709/latest-chrome-extension-breaks-google-sign-in-on-our-website).

If you have the 1Password Chrome extension installed on your browser, could you please try [this fix](https://1password.community/discussion/comment/684528/#Comment_684528) and see if it helps with the Google Auth issue ?

Please let us know if you do not have the extension or if the issue persists even after the fix.
Thanks!

**Comment by jacobmclocklin** [comment]
Wow! That is it! Just a reminder for myself that I should have tested with no extensions enabled. Apologies for the false issue, and I'm glad that it is nothing to fix in this repo. I do hope that the extension owners can resolve this issue for others, so that we don't have to ask every user to change this setting or change their browser. 

Thank you!

**Comment by jlambert23** [comment]
My organization uses 1pass and I ran into this issue as well. Incognito mode with no extensions did not help for some reason, but changing the 1pass setting as described in the [posted fix](https://github.com/thoughtworks/build-your-own-radar/issues/314#issuecomment-1530933586) settled my issue.

Just wanted to say thanks for solving this already! 👍
