### ISSUE TITLE
Can't find the Google Sheet 

### ISSUE THREAD

**Issue by gullywompr** [thoughtworks/build-your-own-radar#319]
Same symptoms as seen in https://github.com/thoughtworks/build-your-own-radar/issues/229.  Sheet is shared and accessible by others.

https://docs.google.com/spreadsheets/d/1E9l8Mblt6F5T9fAJl4JR3Crsm5fkr73SHFC3V6OmMr4

**Comment by devansh-sharma-tw** [comment]
Hi @gullywompr , your sheet has been shared correctly, it's actually the column headers in the sheet that are the issue here. They need to match the headers we've listed in the [example here](https://github.com/thoughtworks/build-your-own-radar#setting-up-your-data). Updating your headers to match the list mentioned should fix the issue you have.

The error message stating the "Google Sheet not being found" was actually a code issue in the app, and has been fixed now. Sorry for the confusion there!

Thanks!
