### ISSUE TITLE
Google Sheets Publish to Web URL no longer works - does not contain sheet id

### ISSUE THREAD

**Issue by stephan42** [thoughtworks/build-your-own-radar#7]
Steps to Repro:
1] Copy the data from your current example here https://docs.google.com/spreadsheets/d/1YXkrgV7Y6zShiPeyw4Y5_19QOfu5I6CyH5sGnbkEyiI/pubhtml
2] Publish to web
3] Note that the new pub to web URL format no longer contains the sheet id.  

I used both my corporate and personal accounts and both produced a Web pubhtml URL format that did not work.  

I was able to get it to work with that same sheet by using the Google Sheet URL itself and copying the sheet ID from it directly.  See http://stackoverflow.com/questions/11339500/how-to-fetch-the-id-of-a-google-spread-sheet-via-google-apps-script

**Comment by rdoh** [comment]
Thank you for reporting. We will fix this shortly.

**Comment by arunvelsriram** [comment]
Thank you for reporting this.

Sheet ID is the key to get access to data on a particular sheet. Since this was removed from the new URL format, we have changed the way of sharing the sheet with the service. So, now you can build the Radar using just the Google sheet URL that appears on the browser's address bar, provided your sheet is "Published to the Web" already. Internally we just extract the sheet ID from the input URL and send it to `tabletop.js`.

Google supports access to the sheet with the old "Publish to Web" URL format. So the service will also work with the old "Publish to Web" URL, which means users who have already created and shared their own Radar are not affected.

We are working on improving the homepage, instructions, FAQ and Github README content to ease the usage of the tool. Meanwhile, you can follow the below steps to get your Radar ready:

1. Create a Google sheet and populate it with your data
2. Click File -> Publish to Web -> Publish
3. Close the "Publish to Web" dialog
4. Copy the URL of your sheet from the browser's address bar
5. Input the URL or just the Sheet ID to [https://radar.thoughtworks.com](https://radar.thoughtworks.com)

**Comment by stephan42** [comment]
Thank you for the feedback - great response!  I have another issue I discovered while using it extensively for the last few days.  Perhaps it is a google issue though.  I'll open a new ticket for your review.  Great tool - our CTO was impressed by our plan using this tool!
