### ISSUE TITLE
Line breaks in description

### ISSUE THREAD

**Issue by gustavz** [thoughtworks/build-your-own-radar#89]
Probably a easy one.
How to get line-breaks inside the descirption?
neither `\n`nor `< b/>` works, putting double quotation marks `""` around them does not help either. I thought CSV and HTML format should support this.

Does this need to be added in the `InputSanitizer` ?

**Comment by micheldrescher** [comment]
I just checked InputSanitizer and it indeed allows the HTML tags for bold and newline, i.e. '"b"' and '"br"'. 
But I suspect it being unable to detect collapsed HTML tags, only full tag use such as `<b>...</b>` but not `<br/>`.  `\n` is invalid HTML.

I suggest using '<p>...</p>' instead of '<br/>' anyway.

**Comment by jean** [comment]
@gustavz could you close this issue? It looks like you got a reasonable answer.
